#!/bin/sh
#
# A hook script that is called after a successful merge
# to record the commit-id in the working directory.
git log -1 --pretty="SIM_GIT_COMMIT_ID %H%nSIM_GIT_COMMIT_TIME %aI" >.git-commit-id

